name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Build:checkout"
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v3     
      with:
        context: site 
        push: true
        registry: ghcr.io
        username: "defjef1979"
        password: ${{ secrets.PAT }}
        repository: defjef1979/graafsite
        tags: defjef1979/graafschap:0.1,defjef1979/graafsite:latest
