name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Build:checkout"
      uses: actions/checkout@v3

    - uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}       

    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v3     
      with:
        registry: ${{ env.REGISTRY }}
        context: site 
        push: true
        tags: ${{ env.REGISTRY }}/defjef1979/graafschap
