name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Build:checkout"
      uses: actions/checkout@v3
    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v3     
      with:
        working-directory: site 
        registry: ghcr.io
        username: "defjef1979"
        password: ${{ secrets.PAT }}
        repository: defjef1979/graafsite
        tags: latest
