name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Build:checkout"
      uses: actions/checkout@v3

    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}       
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 'Build:dockerimage'
      uses: docker/build-push-action@v3     
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: site 
        push: true
        tags: defjef1979/graafschap:0.1,defjef1979/graafsite:latest
